name: Applus Energie
description: 
  
url: "http://applus.github.io"

paginate: 10

markdown: rdiscount

# translation tags
t:
  ita:
    home:  "Hme"
    about: "About"
    developer : "Sviluppatori"
    documentation : "Documentazione"
    demo : "Demo online"
    use : "Usa online"
    contact : "Contatti"
    language : "Lingua"
    components : "Componenti"
    installation : "Installazione"
    desk_dashboard : "Dashboard consumi elettrici"
    ist_tablet : "Consumo istantaneo"
    last_h_smart : "Consumo delle ultime ore"
    last_d_smart : "Consumo degli ultimi giorni"
    desk_dashboard_clim : "Dashboard climatica"
    clim_menu : "Menù di navigazione climatico"
    ist_uta : "Valori istantanei UTA"
    back_to_top : "Torna su"
  eng:
    home:  "Home"
    about: "About"
    developer : "Developer"
    documentation : "Documentation"
    demo : "Online demo"
    use : "Online use"
    contact : "Contact"
    language : "Language"
    components : "Components"
    installation : "Installation"
    desk_dashboard : "Electric consumption dashboard"
    ist_tablet : "Instant consumption"
    last_h_smart : "Last hours consumption"
    last_d_smart : "Last days consumption"
    desk_dashboard_clim : "Climatic dashboard"
    clim_menu : "Climatic navigation menu"
    ist_uta : "AHU current values"
    back_to_top : "Back to top"